---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

env:
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: 1

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Apple Silicon
            target: aarch64-apple-darwin
            arch: arm64
            host: macos-latest
            os: darwin
          - name: Apple x86_64
            target: x86_64-apple-darwin
            arch: amd64
            host: macos-latest
            os: darwin

    runs-on: ${{ matrix.host }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: ${{ matrix.target }}
          toolchain: stable

      - uses: swatinem/rust-cache@v2
      - uses: extractions/setup-just@v1

      - name: Versions
        run: |
          git version
          cargo version

      - name: Format Check
        run: just format-check

      - name: Clippy
        run: just lint

      - name: Build & Test
        id: build
        run: |
          cargo build --release --target ${{ matrix.target }}
          cargo test
