---
name: Release

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: aarch64-apple-darwin, x86_64-apple-darwin
          toolchain: stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Build aarch64 & x86_64
        run: |
          cargo build --release --target=aarch64-apple-darwin
          cargo build --release --target=x86_64-apple-darwin

      - name: Create Universal Binary
        run: |
          lipo target/x86_64-apple-darwin/release/macos-defaults target/aarch64-apple-darwin/release/macos-defaults -create -output ./macos-defaults
          strip ./macos-defaults

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-defaults
          path: ./macos-defaults
